version: "3"

tasks:
  setup:
    dir: .
    cmds:
      - pre-commit install
      - if [ ! -f .act.secrets ]; then cp .act.secrets.example .act.secrets ; fi
      - if [ ! -f discord-bot/.env ]; then cp discord-bot/.env.example discord-bot/.env ; fi

  test:
    cmds:
      - docker-compose exec -T discord-bot isort ./app --check-only
      - docker-compose exec -T discord-bot black ./app --check
      - docker-compose exec -T discord-bot mypy ./app
      - docker-compose exec -T discord-bot pylint --recursive=y ./app
